import RestaurantCard from '$/lib/components/restaurants/RestaurantCard';
import { api } from '$/utils/api';
import Head from 'next/head';

const Restaurants = () => {
    const { data: getAllRestaurants } = api.restaurant.getAll.useQuery();

    type Restaurant = {
        id: number;
        name: string;
        address: string;
        phone: string;
    };

    return (
        <>
        <Head>
        <title>Restaurants</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='p-20'>
            <h1 className='text-3xl text-white font-bold mb-6'>Restaurants</h1>
            <div className='grid grid-cols-3'>
            {getAllRestaurants ? (
                getAllRestaurants.map((restaurant: Restaurant) => (
                    <div className='bg-white p-2 my-3 mx-4 rounded-xl'>
                    <RestaurantCard
                        key={restaurant.id}
                        name={restaurant.name}
                        address={restaurant.address}
                        phoneNumber={restaurant.phone}
                    />
                    </div>
                ))
            ) : (
                <p>Loading restaurants...</p>
            )}
            </div>
            
        </div>
        </>
    );
};

export default Restaurants;
            